// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEiiawnfjFxc1Hg9_ZhL_WltUGqAXyFpI',
    appId: '1:365467431876:web:2e3e26c14b9311fa1e6a91',
    messagingSenderId: '365467431876',
    projectId: 'ngoorg',
    authDomain: 'ngoorg.firebaseapp.com',
    storageBucket: 'ngoorg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcggAT7Vow1Fa9T9ei3nbBhXrdKY9HGQU',
    appId: '1:365467431876:android:b6b96567559350ec1e6a91',
    messagingSenderId: '365467431876',
    projectId: 'ngoorg',
    storageBucket: 'ngoorg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPkqQd4kImUwssQNA3oMsfRQDKAFNQWqE',
    appId: '1:365467431876:ios:f387b788426096db1e6a91',
    messagingSenderId: '365467431876',
    projectId: 'ngoorg',
    storageBucket: 'ngoorg.firebasestorage.app',
    iosBundleId: 'com.example.peepalfram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPkqQd4kImUwssQNA3oMsfRQDKAFNQWqE',
    appId: '1:365467431876:ios:f387b788426096db1e6a91',
    messagingSenderId: '365467431876',
    projectId: 'ngoorg',
    storageBucket: 'ngoorg.firebasestorage.app',
    iosBundleId: 'com.example.peepalfram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEiiawnfjFxc1Hg9_ZhL_WltUGqAXyFpI',
    appId: '1:365467431876:web:65b2a79e7b01ca891e6a91',
    messagingSenderId: '365467431876',
    projectId: 'ngoorg',
    authDomain: 'ngoorg.firebaseapp.com',
    storageBucket: 'ngoorg.firebasestorage.app',
  );
}
